#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = random.randint(1, 10)  # TODO: edit here
    b = random.randint(1, 10)  # TODO: edit here
    c = [None for _ in range(b)]
    d = [None for _ in range(b)]
    for i in range(b):
        c[i] = random.randint(1, 10)  # TODO: edit here
        d[i] = random.randint(1, 10)  # TODO: edit here
    e = random.randint(1, 10)  # TODO: edit here
    f = random.randint(1, 10)  # TODO: edit here
    g = random.randint(1, 10)  # TODO: edit here
    print(a, b)
    for i in range(b):
        print(c[i])
        print(d[i], end=' ')
    print(e)
    print(f, g)


if __name__ == "__main__":
    main()
